name: Update Post45 Theme Submodule

on:
  push:
    paths:
      - 'plugins/themes/post45'
  workflow_dispatch:  # Add this line to allow manual triggering

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update submodule
      run: |
        cd plugins/themes/post45
        git pull origin main

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .  # Deploy the updated repository